# Importing the Dependencies

In [1]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Difflib

Difflib is a built-in module in the Python programming language consisting of different simple functions and classes that allow users to compare data sets. 

Cosine Similarity

cosine similarity metric measures the cosine of the angle between two n-dimensional vectors projected in a multi-dimensional space. The Cosine similarity of two documents will range from 0 to 1. If the Cosine similarity score is 1, it means two vectors have the same orientation. The value closer to 0 indicates that the two documents have less similarity.

# Data Collection and Processing

In [2]:
df=pd.read_csv("movies.csv")
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [3]:
#number of rows and columns
df.shape

(2889, 24)

In [4]:
#select the relevant features for recommendations
selected_features=['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [5]:
#replacing the null values with null string
for features in selected_features:
    df[features]=df[features].fillna('')

In [6]:
#combining all the 5 selected features
combined_features=df['genres']+' '+df['keywords']+' '+df['tagline']+' '+df['cast']+' '+df['director']

In [7]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
2884    Fantasy Drama Science Fiction Romance free lov...
2885    Crime Drama Romance sex jealousy lover (female...
2886    Adventure Drama Family adolescence loss of fat...
2887    Drama Romance alcohol mermaid wedding dress fi...
2888    Crime Drama Thriller brother brother relations...
Length: 2889, dtype: object


In [8]:
#converting the text data to feature vectors
vectorizer=TfidfVectorizer()

feature_vectors=vectorizer.fit_transform(combined_features)

print(feature_vectors)

  (0, 1609)	0.17216367989508619
  (0, 5247)	0.11649458084652754
  (0, 8784)	0.19207623983771868
  (0, 6884)	0.16023920352821944
  (0, 5902)	0.23171815538485757
  (0, 9859)	0.15689699123807493
  (0, 11264)	0.19619974579438337
  (0, 9481)	0.20262554094571583
  (0, 8986)	0.21289649690715384
  (0, 11699)	0.20840541155499975
  (0, 11517)	0.2277567373559447
  (0, 9009)	0.1503134786586281
  (0, 7733)	0.26470656211518784
  (0, 7530)	0.09112675731439052
  (0, 11513)	0.12448156565527596
  (0, 10298)	0.0695967582582661
  (0, 3318)	0.24139381828533002
  (0, 9623)	0.21538898366757647
  (0, 2142)	0.24752587200697213
  (0, 11200)	0.12396544534954293
  (0, 9698)	0.3301815531496929
  (0, 3940)	0.16451583642216483
  (0, 2040)	0.23620924073701163
  (0, 2461)	0.24139381828533002
  (0, 3656)	0.10082386311001892
  :	:
  (2888, 5560)	0.22049690504172229
  (2888, 6589)	0.22049690504172229
  (2888, 10260)	0.22049690504172229
  (2888, 10065)	0.22049690504172229
  (2888, 6442)	0.22049690504172229
  (2888, 5722)	

# Cosine Similarity

In [9]:
#getting the similarity score using cosine similarity
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.06683611 0.03595506 ... 0.01351358 0.00392269 0.10253377]
 [0.06683611 1.         0.02980265 ... 0.02376891 0.01034938 0.        ]
 [0.03595506 0.02980265 1.         ... 0.00627966 0.         0.01597373]
 ...
 [0.01351358 0.02376891 0.00627966 ... 1.         0.00273352 0.01756207]
 [0.00392269 0.01034938 0.         ... 0.00273352 1.         0.01745094]
 [0.10253377 0.         0.01597373 ... 0.01756207 0.01745094 1.        ]]


In [10]:
similarity.shape

(2889, 2889)

In [11]:
#getting the movie name from the user
movie_name=input("Enter your favourite movie name:")

Enter your favourite movie name:Iron man


In [12]:
#creating a list with all the movie names given in the dataset
list_of_all_titles=df['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [13]:
#finding the close match for the movie name given by the user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)

In [14]:
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [15]:
close_match=find_close_match[0]
print(close_match)

Iron Man


In [16]:
#finding the index of the movie with title

index_of_the_movie=df[df.title==close_match]['index'].values[0]
print(index_of_the_movie)

68


# Enumerate

Python's enumerate() lets you write Pythonic for loops when you need a count and the value from an iterable. The big advantage of enumerate() is that it returns a tuple with the counter and value, so you don't have to increment the counter yourself.

In [17]:
#getting a list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.0304259820807854), (1, 0.05392446616507077), (2, 0.011738104489086531), (3, 0.005598455154444208), (4, 0.02912170990765474), (5, 0.011768930684782495), (6, 0.07800305501320266), (7, 0.2284871039281643), (8, 0.006561246647518155), (9, 0.07047490016651674), (10, 0.07063645305467237), (11, 0.009977603138321451), (12, 0.011634587680873597), (13, 0.010227132332183754), (14, 0.09054363193329532), (15, 0.0060316701499069595), (16, 0.21783153118072396), (17, 0.011069410081664406), (18, 0.03988535844845614), (19, 0.08028453111145392), (20, 0.07199294412343234), (21, 0.009544349244210975), (22, 0.005809126123899533), (23, 0.005490379800384789), (24, 0.01023495128799077), (25, 0.0), (26, 0.20625874803453675), (27, 0.0278204428914701), (28, 0.05849645033081331), (29, 0.01181204997106447), (30, 0.07298784980634242), (31, 0.3009684390226492), (32, 0.02879828601860423), (33, 0.12107206421830344), (34, 0.0), (35, 0.03230380275482796), (36, 0.02916082577656449), (37, 0.006631063167402816), (38, 

In [18]:
#sorting the movies based on their similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)

[(68, 1.0), (79, 0.3941660922983351), (31, 0.3009684390226492), (7, 0.2284871039281643), (16, 0.21783153118072396), (26, 0.20625874803453675), (85, 0.1969605074076875), (182, 0.18402163199967156), (511, 0.15693558579846079), (64, 0.142424527095605), (203, 0.13803710881782194), (174, 0.1353418537565019), (101, 0.13324910226957815), (46, 0.1331160305935528), (1740, 0.12808468354408203), (131, 0.12785042240697791), (169, 0.12721634082477046), (94, 0.12653471999569724), (126, 0.12440381350165987), (788, 0.12342995270989897), (33, 0.12107206421830344), (783, 0.12028929496894512), (138, 0.11818426683085964), (2487, 0.1180357620176451), (2442, 0.11748210941851377), (661, 0.11392616867395192), (2651, 0.10952455916708484), (607, 0.1092952075159471), (353, 0.10869322801631445), (1451, 0.10835170056432078), (1553, 0.10764302918434457), (38, 0.10193170945860613), (618, 0.10034719298774107), (122, 0.09892666580534956), (1210, 0.0988253020184461), (720, 0.0979030440095321), (954, 0.0966433002257457)

In [19]:
#print the name of similar movies based on the index
print("Movies suggested for you :\n")
i=1

for movie in sorted_similar_movies:
    index=movie[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if (i<30):
        print(i,'.',title_from_index)
        i+=1

Movies suggested for you :

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . X-Men: Apocalypse
11 . X2
12 . The Incredible Hulk
13 . X-Men: First Class
14 . X-Men: Days of Future Past
15 . Kick-Ass 2
16 . G-Force
17 . Captain America: The First Avenger
18 . Guardians of the Galaxy
19 . Thor: The Dark World
20 . Deadpool
21 . X-Men: The Last Stand
22 . Mortdecai
23 . The Last Airbender
24 . Duets
25 . Southland Tales
26 . Zathura: A Space Adventure
27 . The Good Night
28 . Sky Captain and the World of Tomorrow
29 . Tropic Thunder


In [20]:
#getting the movie name from the user
movie_name=input("Enter your favourite movie name:")
#creating a list with all the movie names given in the dataset
list_of_all_titles=df['title'].tolist()
#finding the close match for the movie name given by the user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
#finding the index of the movie with title
index_of_the_movie=df[df.title==close_match]['index'].values[0]
#getting a list of similar movies
similarity_score=list(enumerate(similarity[index_of_the_movie]))
#sorting the movies based on their similarity score
sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
#print the name of similar movies based on the index
print("Movies suggested for you :\n")
i=1
for movie in sorted_similar_movies:
    index=movie[0]
    title_from_index=df[df.index==index]['title'].values[0]
    if (i<30):
        print(i,'.',title_from_index)
        i+=1

Enter your favourite movie name:batman
Movies suggested for you :

1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . Bedazzled
8 . A History of Violence
9 . Superman
10 . Beetlejuice
11 . The Sentinel
12 . Planet of the Apes
13 . Mars Attacks!
14 . Man of Steel
15 . Suicide Squad
16 . The Postman Always Rings Twice
17 . The Mask
18 . Salton Sea
19 . Exorcist II: The Heretic
20 . Spider-Man 3
21 . The Land Before Time
22 . Dungeons & Dragons: Wrath of the Dragon God
23 . Spider-Man 2
24 . Jonah Hex
25 . Superman Returns
26 . Green Lantern
27 . I Dreamed of Africa
28 . Reds
29 . Superman II
